apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: ephemeral-local-
commonAnnotations:
  note: Hello, I am an ephemeral environment (using a remote base)!
resources:
  - https://github.com/releasehub-com/kustomize-examples//hello-world/base
configMapGenerator:
  - name: the-map
    behavior: merge
    literals:
      - greeting=placeholder
